// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Route struct {
	ID               pgtype.UUID
	Name             pgtype.Text
	Source           string
	Geometry         interface{}
	DistanceMeters   int32
	DurationSeconds  int32
	DifficultyScore  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	OriginalPolyline string
}

type RouteAnalysis struct {
	ID                pgtype.UUID
	RouteID           pgtype.UUID
	EngineVersion     string
	DifficultyScore   pgtype.Numeric
	AverageDifficulty pgtype.Numeric
	PeakDifficulty    pgtype.Numeric
	ComplexityScore   pgtype.Numeric
	AnalyzedAt        pgtype.Timestamptz
}

type RouteCategoryScore struct {
	RouteAnalysisID pgtype.UUID
	Category        string
	Score           pgtype.Numeric
}

type RouteEvent struct {
	ID                  pgtype.UUID
	RouteID             pgtype.UUID
	SegmentID           pgtype.UUID
	Type                string
	Position            interface{}
	RouteDistanceMeters pgtype.Int4
	DifficultyScore     pgtype.Numeric
	Metadata            []byte
	CreatedAt           pgtype.Timestamptz
}

type RouteSegment struct {
	ID                pgtype.UUID
	RouteID           pgtype.UUID
	Sequence          int32
	Geometry          interface{}
	DistanceMeters    int32
	DurationSeconds   pgtype.Int4
	RoadClass         pgtype.Text
	RoadName          pgtype.Text
	SpeedLimitKph     pgtype.Int4
	ElevationStartM   pgtype.Float8
	ElevationEndM     pgtype.Float8
	InclineAvgPercent pgtype.Float8
	InclineMaxPercent pgtype.Float8
	CurveScore        pgtype.Numeric
	DifficultyScore   pgtype.Numeric
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
}
