// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
    id,
    source,
    geometry,
    distance_meters,
    duration_seconds,
    original_polyline
) VALUES (
    gen_random_uuid(),
    $1,
    ST_GeogFromText($2::text),
    $3,
    $4,
    $5
)
RETURNING
    id::text,
    source,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    original_polyline,
    created_at
`

type CreateRouteParams struct {
	Source           string
	GeometryWkt      string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
}

type CreateRouteRow struct {
	ID               string
	Source           string
	GeometryGeojson  string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (CreateRouteRow, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Source,
		arg.GeometryWkt,
		arg.DistanceMeters,
		arg.DurationSeconds,
		arg.OriginalPolyline,
	)
	var i CreateRouteRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.GeometryGeojson,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.OriginalPolyline,
		&i.CreatedAt,
	)
	return i, err
}

const createRouteAnalysis = `-- name: CreateRouteAnalysis :one
INSERT INTO route_analyses (
    id,
    route_id,
    engine_version,
    difficulty_score,
    average_difficulty,
    peak_difficulty,
    complexity_score
) VALUES (
    gen_random_uuid(),
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id::text,
    route_id::text,
    engine_version,
    difficulty_score,
    average_difficulty,
    peak_difficulty,
    complexity_score,
    analyzed_at
`

type CreateRouteAnalysisParams struct {
	RouteID           pgtype.UUID
	EngineVersion     string
	DifficultyScore   pgtype.Numeric
	AverageDifficulty pgtype.Numeric
	PeakDifficulty    pgtype.Numeric
	ComplexityScore   pgtype.Numeric
}

type CreateRouteAnalysisRow struct {
	ID                string
	RouteID           string
	EngineVersion     string
	DifficultyScore   pgtype.Numeric
	AverageDifficulty pgtype.Numeric
	PeakDifficulty    pgtype.Numeric
	ComplexityScore   pgtype.Numeric
	AnalyzedAt        pgtype.Timestamptz
}

func (q *Queries) CreateRouteAnalysis(ctx context.Context, arg CreateRouteAnalysisParams) (CreateRouteAnalysisRow, error) {
	row := q.db.QueryRow(ctx, createRouteAnalysis,
		arg.RouteID,
		arg.EngineVersion,
		arg.DifficultyScore,
		arg.AverageDifficulty,
		arg.PeakDifficulty,
		arg.ComplexityScore,
	)
	var i CreateRouteAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.EngineVersion,
		&i.DifficultyScore,
		&i.AverageDifficulty,
		&i.PeakDifficulty,
		&i.ComplexityScore,
		&i.AnalyzedAt,
	)
	return i, err
}

const createRouteCategoryScore = `-- name: CreateRouteCategoryScore :one
INSERT INTO route_category_scores (
    route_analysis_id,
    category,
    score
) VALUES (
    $1::uuid,
    $2,
    $3
)
RETURNING
    route_analysis_id::text,
    category,
    score
`

type CreateRouteCategoryScoreParams struct {
	RouteAnalysisID pgtype.UUID
	Category        string
	Score           pgtype.Numeric
}

type CreateRouteCategoryScoreRow struct {
	RouteAnalysisID string
	Category        string
	Score           pgtype.Numeric
}

func (q *Queries) CreateRouteCategoryScore(ctx context.Context, arg CreateRouteCategoryScoreParams) (CreateRouteCategoryScoreRow, error) {
	row := q.db.QueryRow(ctx, createRouteCategoryScore, arg.RouteAnalysisID, arg.Category, arg.Score)
	var i CreateRouteCategoryScoreRow
	err := row.Scan(&i.RouteAnalysisID, &i.Category, &i.Score)
	return i, err
}

const createRouteEvent = `-- name: CreateRouteEvent :one
INSERT INTO route_events (
    id,
    route_id,
    segment_id,
    type,
    position,
    route_distance_meters,
    difficulty_score,
    metadata
) VALUES (
    gen_random_uuid(),
    $1::uuid,
    $2::uuid,
    $3,
    ST_GeogFromText($4::text),
    $5,
    $6,
    $7
)
RETURNING
    id::text,
    route_id::text,
    COALESCE(segment_id::text, '')::text AS segment_id,
    type,
    ST_AsGeoJSON(position::geometry)::text AS position_geojson,
    route_distance_meters,
    difficulty_score,
    metadata,
    created_at
`

type CreateRouteEventParams struct {
	RouteID             pgtype.UUID
	SegmentID           pgtype.UUID
	Type                string
	PositionWkt         string
	RouteDistanceMeters pgtype.Int4
	DifficultyScore     pgtype.Numeric
	Metadata            []byte
}

type CreateRouteEventRow struct {
	ID                  string
	RouteID             string
	SegmentID           string
	Type                string
	PositionGeojson     string
	RouteDistanceMeters pgtype.Int4
	DifficultyScore     pgtype.Numeric
	Metadata            []byte
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateRouteEvent(ctx context.Context, arg CreateRouteEventParams) (CreateRouteEventRow, error) {
	row := q.db.QueryRow(ctx, createRouteEvent,
		arg.RouteID,
		arg.SegmentID,
		arg.Type,
		arg.PositionWkt,
		arg.RouteDistanceMeters,
		arg.DifficultyScore,
		arg.Metadata,
	)
	var i CreateRouteEventRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.SegmentID,
		&i.Type,
		&i.PositionGeojson,
		&i.RouteDistanceMeters,
		&i.DifficultyScore,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createRouteSegment = `-- name: CreateRouteSegment :one
INSERT INTO route_segments (
    id,
    route_id,
    sequence,
    geometry,
    distance_meters,
    duration_seconds,
    road_class,
    road_name,
    road_use,
    speed_limit_kph,
    elevation_start_m,
    elevation_end_m,
    incline_avg_percent,
    incline_max_percent
) VALUES (
    gen_random_uuid(),
    $1::uuid,
    $2,
    ST_GeogFromText($3::text),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING
    id::text,
    route_id::text,
    sequence,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    road_class,
    road_name,
    road_use,
    speed_limit_kph,
    elevation_start_m,
    elevation_end_m,
    incline_avg_percent,
    incline_max_percent,
    created_at
`

type CreateRouteSegmentParams struct {
	RouteID           pgtype.UUID
	Sequence          int32
	GeometryWkt       string
	DistanceMeters    int32
	DurationSeconds   pgtype.Int4
	RoadClass         pgtype.Text
	RoadName          pgtype.Text
	RoadUse           pgtype.Text
	SpeedLimitKph     pgtype.Int4
	ElevationStartM   pgtype.Float8
	ElevationEndM     pgtype.Float8
	InclineAvgPercent pgtype.Float8
	InclineMaxPercent pgtype.Float8
}

type CreateRouteSegmentRow struct {
	ID                string
	RouteID           string
	Sequence          int32
	GeometryGeojson   string
	DistanceMeters    int32
	DurationSeconds   pgtype.Int4
	RoadClass         pgtype.Text
	RoadName          pgtype.Text
	RoadUse           pgtype.Text
	SpeedLimitKph     pgtype.Int4
	ElevationStartM   pgtype.Float8
	ElevationEndM     pgtype.Float8
	InclineAvgPercent pgtype.Float8
	InclineMaxPercent pgtype.Float8
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateRouteSegment(ctx context.Context, arg CreateRouteSegmentParams) (CreateRouteSegmentRow, error) {
	row := q.db.QueryRow(ctx, createRouteSegment,
		arg.RouteID,
		arg.Sequence,
		arg.GeometryWkt,
		arg.DistanceMeters,
		arg.DurationSeconds,
		arg.RoadClass,
		arg.RoadName,
		arg.RoadUse,
		arg.SpeedLimitKph,
		arg.ElevationStartM,
		arg.ElevationEndM,
		arg.InclineAvgPercent,
		arg.InclineMaxPercent,
	)
	var i CreateRouteSegmentRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Sequence,
		&i.GeometryGeojson,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.RoadClass,
		&i.RoadName,
		&i.RoadUse,
		&i.SpeedLimitKph,
		&i.ElevationStartM,
		&i.ElevationEndM,
		&i.InclineAvgPercent,
		&i.InclineMaxPercent,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRouteAnalysis = `-- name: GetLatestRouteAnalysis :one
SELECT
    id::text,
    route_id::text,
    engine_version,
    difficulty_score,
    average_difficulty,
    peak_difficulty,
    complexity_score,
    analyzed_at
FROM route_analyses
WHERE route_id = $1::uuid
ORDER BY analyzed_at DESC
LIMIT 1
`

type GetLatestRouteAnalysisRow struct {
	ID                string
	RouteID           string
	EngineVersion     string
	DifficultyScore   pgtype.Numeric
	AverageDifficulty pgtype.Numeric
	PeakDifficulty    pgtype.Numeric
	ComplexityScore   pgtype.Numeric
	AnalyzedAt        pgtype.Timestamptz
}

func (q *Queries) GetLatestRouteAnalysis(ctx context.Context, routeID pgtype.UUID) (GetLatestRouteAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getLatestRouteAnalysis, routeID)
	var i GetLatestRouteAnalysisRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.EngineVersion,
		&i.DifficultyScore,
		&i.AverageDifficulty,
		&i.PeakDifficulty,
		&i.ComplexityScore,
		&i.AnalyzedAt,
	)
	return i, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT
    id::text,
    source,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    original_polyline,
    created_at
FROM routes
WHERE id = $1::uuid
`

type GetRouteByIDRow struct {
	ID               string
	Source           string
	GeometryGeojson  string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetRouteByID(ctx context.Context, id pgtype.UUID) (GetRouteByIDRow, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i GetRouteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.GeometryGeojson,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.OriginalPolyline,
		&i.CreatedAt,
	)
	return i, err
}

const listRouteCategoryScores = `-- name: ListRouteCategoryScores :many
SELECT
    route_analysis_id::text,
    category,
    score
FROM route_category_scores
WHERE route_analysis_id = $1::uuid
ORDER BY category
`

type ListRouteCategoryScoresRow struct {
	RouteAnalysisID string
	Category        string
	Score           pgtype.Numeric
}

func (q *Queries) ListRouteCategoryScores(ctx context.Context, routeAnalysisID pgtype.UUID) ([]ListRouteCategoryScoresRow, error) {
	rows, err := q.db.Query(ctx, listRouteCategoryScores, routeAnalysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteCategoryScoresRow
	for rows.Next() {
		var i ListRouteCategoryScoresRow
		if err := rows.Scan(&i.RouteAnalysisID, &i.Category, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteEvents = `-- name: ListRouteEvents :many
SELECT
    id::text,
    route_id::text,
    COALESCE(segment_id::text, '')::text AS segment_id,
    type,
    ST_AsGeoJSON(position::geometry)::text AS position_geojson,
    route_distance_meters,
    difficulty_score,
    metadata,
    created_at
FROM route_events
WHERE route_id = $1::uuid
ORDER BY route_distance_meters, created_at
`

type ListRouteEventsRow struct {
	ID                  string
	RouteID             string
	SegmentID           string
	Type                string
	PositionGeojson     string
	RouteDistanceMeters pgtype.Int4
	DifficultyScore     pgtype.Numeric
	Metadata            []byte
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListRouteEvents(ctx context.Context, routeID pgtype.UUID) ([]ListRouteEventsRow, error) {
	rows, err := q.db.Query(ctx, listRouteEvents, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteEventsRow
	for rows.Next() {
		var i ListRouteEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.SegmentID,
			&i.Type,
			&i.PositionGeojson,
			&i.RouteDistanceMeters,
			&i.DifficultyScore,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteSegments = `-- name: ListRouteSegments :many
SELECT
    id::text,
    route_id::text,
    sequence,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    road_class,
    road_name,
    road_use,
    speed_limit_kph,
    elevation_start_m,
    elevation_end_m,
    incline_avg_percent,
    incline_max_percent,
    created_at
FROM route_segments
WHERE route_id = $1::uuid
ORDER BY sequence
`

type ListRouteSegmentsRow struct {
	ID                string
	RouteID           string
	Sequence          int32
	GeometryGeojson   string
	DistanceMeters    int32
	DurationSeconds   pgtype.Int4
	RoadClass         pgtype.Text
	RoadName          pgtype.Text
	RoadUse           pgtype.Text
	SpeedLimitKph     pgtype.Int4
	ElevationStartM   pgtype.Float8
	ElevationEndM     pgtype.Float8
	InclineAvgPercent pgtype.Float8
	InclineMaxPercent pgtype.Float8
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListRouteSegments(ctx context.Context, routeID pgtype.UUID) ([]ListRouteSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listRouteSegments, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteSegmentsRow
	for rows.Next() {
		var i ListRouteSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Sequence,
			&i.GeometryGeojson,
			&i.DistanceMeters,
			&i.DurationSeconds,
			&i.RoadClass,
			&i.RoadName,
			&i.RoadUse,
			&i.SpeedLimitKph,
			&i.ElevationStartM,
			&i.ElevationEndM,
			&i.InclineAvgPercent,
			&i.InclineMaxPercent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
