// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
    id,
    source,
    geometry,
    distance_meters,
    duration_seconds,
    original_polyline
) VALUES (
    gen_random_uuid(),
    $1,
    ST_GeogFromText($2::text),
    $3,
    $4,
    $5
)
RETURNING
    id::text,
    source,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    original_polyline,
    created_at
`

type CreateRouteParams struct {
	Source           string
	GeometryWkt      string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
}

type CreateRouteRow struct {
	ID               string
	Source           string
	GeometryGeojson  string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (CreateRouteRow, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Source,
		arg.GeometryWkt,
		arg.DistanceMeters,
		arg.DurationSeconds,
		arg.OriginalPolyline,
	)
	var i CreateRouteRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.GeometryGeojson,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.OriginalPolyline,
		&i.CreatedAt,
	)
	return i, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT
    id::text,
    source,
    ST_AsGeoJSON(geometry::geometry)::text AS geometry_geojson,
    distance_meters,
    duration_seconds,
    original_polyline,
    created_at
FROM routes
WHERE id = $1::uuid
`

type GetRouteByIDRow struct {
	ID               string
	Source           string
	GeometryGeojson  string
	DistanceMeters   int32
	DurationSeconds  int32
	OriginalPolyline string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetRouteByID(ctx context.Context, id pgtype.UUID) (GetRouteByIDRow, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i GetRouteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.GeometryGeojson,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.OriginalPolyline,
		&i.CreatedAt,
	)
	return i, err
}
