services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: driving_trainer_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 

    ports:
      - "5432:5432"

    volumes:
      - driving_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U driving_user -d driving_trainer"]
      interval: 5s
      timeout: 5s
      retries: 5

  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:3.8.3
    container_name: driving_trainer_valhalla

    restart: unless-stopped

    ports:
      - "8002:8002"

    volumes:
      - ./infrastructure/valhalla/custom_files:/custom_files

    environment:
      tile_urls: https://download.geofabrik.de/south-america/brazil/sul-latest.osm.pbf
      build_elevation: "True"
      build_admins: "True"
      build_time_zones: "True"
      build_tar: "True"
      server_threads: "2"

volumes:
  driving_postgres_data:
