services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: driving_trainer_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: driving_trainer
      POSTGRES_USER: driving_user
      POSTGRES_PASSWORD: driving_password

    ports:
      - "5432:5432"

    volumes:
      - driving_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U driving_user -d driving_trainer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  driving_postgres_data: